/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as EmailTestingRouteImport } from './routes/email-testing'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as NotificationsTemplatesRouteImport } from './routes/notifications.templates'
import { Route as NotificationsSchedulesRouteImport } from './routes/notifications.schedules'
import { Route as LearnCoursesRouteImport } from './routes/learn.courses'
import { Route as InterviewsAssessmentsRouteImport } from './routes/interviews.assessments'
import { Route as InterviewsSessionIdRouteImport } from './routes/interviews.$sessionId'
import { Route as InterviewTokenRouteImport } from './routes/interview.$token'
import { Route as HiringReportsRouteImport } from './routes/hiring.reports'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as ClassesNewRouteImport } from './routes/classes.new'
import { Route as ClassesClassIdRouteImport } from './routes/classes.$classId'
import { Route as AttemptAssignmentIdRouteImport } from './routes/attempt.$assignmentId'
import { Route as AssessmentsTemplatesRouteImport } from './routes/assessments.templates'
import { Route as AssessmentsBuilderRouteImport } from './routes/assessments.builder'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AssessmentsAssessmentIdPreviewRouteImport } from './routes/assessments.$assessmentId.preview'
import { Route as ApiWebhooksSesRouteImport } from './routes/api/webhooks/ses'
import { Route as ApiClassesSectionAssetRouteImport } from './routes/api/classes/section-asset'
import { Route as ApiClassesFinalizeRouteImport } from './routes/api/classes/finalize'
import { Route as ApiClassesCreateRouteImport } from './routes/api/classes/create'
import { Route as ApiAuthRolesRouteImport } from './routes/api/auth/roles'
import { Route as ApiAuthBootstrapRouteImport } from './routes/api/auth/bootstrap'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'
import { Route as LearnCoursesCourseIdStudyRouteImport } from './routes/learn.courses.$courseId.study'
import { Route as ApiPublicHooksWeeklySummaryRouteImport } from './routes/api/public/hooks/weekly-summary'
import { Route as ApiPublicHooksRetryFailedRouteImport } from './routes/api/public/hooks/retry-failed'
import { Route as ApiPublicHooksEscalationsRouteImport } from './routes/api/public/hooks/escalations'
import { Route as ApiPublicHooksDailyRemindersRouteImport } from './routes/api/public/hooks/daily-reminders'
import { Route as ApiInternalEmailSendResultRouteImport } from './routes/api/internal/email/send-result'
import { Route as ApiInternalEmailProcessRouteImport } from './routes/api/internal/email/process'
import { Route as ApiInternalCronTickRouteImport } from './routes/api/internal/cron/tick'
import { Route as ApiInternalAssetsUploadRouteImport } from './routes/api/internal/assets/upload'
import { Route as ApiInternalAssetsDeleteRouteImport } from './routes/api/internal/assets/delete'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTestingRoute = EmailTestingRouteImport.update({
  id: '/email-testing',
  path: '/email-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterviewsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessmentsRoute,
} as any)
const NotificationsTemplatesRoute = NotificationsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => NotificationsRoute,
} as any)
const NotificationsSchedulesRoute = NotificationsSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => NotificationsRoute,
} as any)
const LearnCoursesRoute = LearnCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LearnRoute,
} as any)
const InterviewsAssessmentsRoute = InterviewsAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => InterviewsRoute,
} as any)
const InterviewsSessionIdRoute = InterviewsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => InterviewsRoute,
} as any)
const InterviewTokenRoute = InterviewTokenRouteImport.update({
  id: '/interview/$token',
  path: '/interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringReportsRoute = HiringReportsRouteImport.update({
  id: '/hiring/reports',
  path: '/hiring/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const ClassesNewRoute = ClassesNewRouteImport.update({
  id: '/classes/new',
  path: '/classes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClassIdRoute = ClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptAssignmentIdRoute = AttemptAssignmentIdRouteImport.update({
  id: '/attempt/$assignmentId',
  path: '/attempt/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsTemplatesRoute = AssessmentsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AssessmentsRoute,
} as any)
const AssessmentsBuilderRoute = AssessmentsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AssessmentsRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsAssessmentIdPreviewRoute =
  AssessmentsAssessmentIdPreviewRouteImport.update({
    id: '/$assessmentId/preview',
    path: '/$assessmentId/preview',
    getParentRoute: () => AssessmentsRoute,
  } as any)
const ApiWebhooksSesRoute = ApiWebhooksSesRouteImport.update({
  id: '/api/webhooks/ses',
  path: '/api/webhooks/ses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesSectionAssetRoute = ApiClassesSectionAssetRouteImport.update({
  id: '/api/classes/section-asset',
  path: '/api/classes/section-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesFinalizeRoute = ApiClassesFinalizeRouteImport.update({
  id: '/api/classes/finalize',
  path: '/api/classes/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassesCreateRoute = ApiClassesCreateRouteImport.update({
  id: '/api/classes/create',
  path: '/api/classes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRolesRoute = ApiAuthRolesRouteImport.update({
  id: '/api/auth/roles',
  path: '/api/auth/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthBootstrapRoute = ApiAuthBootstrapRouteImport.update({
  id: '/api/auth/bootstrap',
  path: '/api/auth/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCoursesCourseIdStudyRoute =
  LearnCoursesCourseIdStudyRouteImport.update({
    id: '/$courseId/study',
    path: '/$courseId/study',
    getParentRoute: () => LearnCoursesRoute,
  } as any)
const ApiPublicHooksWeeklySummaryRoute =
  ApiPublicHooksWeeklySummaryRouteImport.update({
    id: '/api/public/hooks/weekly-summary',
    path: '/api/public/hooks/weekly-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetryFailedRoute =
  ApiPublicHooksRetryFailedRouteImport.update({
    id: '/api/public/hooks/retry-failed',
    path: '/api/public/hooks/retry-failed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEscalationsRoute =
  ApiPublicHooksEscalationsRouteImport.update({
    id: '/api/public/hooks/escalations',
    path: '/api/public/hooks/escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRemindersRoute =
  ApiPublicHooksDailyRemindersRouteImport.update({
    id: '/api/public/hooks/daily-reminders',
    path: '/api/public/hooks/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalEmailSendResultRoute =
  ApiInternalEmailSendResultRouteImport.update({
    id: '/api/internal/email/send-result',
    path: '/api/internal/email/send-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalEmailProcessRoute = ApiInternalEmailProcessRouteImport.update({
  id: '/api/internal/email/process',
  path: '/api/internal/email/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCronTickRoute = ApiInternalCronTickRouteImport.update({
  id: '/api/internal/cron/tick',
  path: '/api/internal/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAssetsUploadRoute = ApiInternalAssetsUploadRouteImport.update({
  id: '/api/internal/assets/upload',
  path: '/api/internal/assets/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAssetsDeleteRoute = ApiInternalAssetsDeleteRouteImport.update({
  id: '/api/internal/assets/delete',
  path: '/api/internal/assets/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/email-testing': typeof EmailTestingRoute
  '/executive': typeof ExecutiveRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/invites': typeof InvitesRoute
  '/learn': typeof LearnRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/api/health': typeof ApiHealthRoute
  '/assessments/builder': typeof AssessmentsBuilderRoute
  '/assessments/templates': typeof AssessmentsTemplatesRoute
  '/attempt/$assignmentId': typeof AttemptAssignmentIdRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/classes/new': typeof ClassesNewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/hiring/reports': typeof HiringReportsRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/interviews/$sessionId': typeof InterviewsSessionIdRoute
  '/interviews/assessments': typeof InterviewsAssessmentsRoute
  '/learn/courses': typeof LearnCoursesRouteWithChildren
  '/notifications/schedules': typeof NotificationsSchedulesRoute
  '/notifications/templates': typeof NotificationsTemplatesRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/bootstrap': typeof ApiAuthBootstrapRoute
  '/api/auth/roles': typeof ApiAuthRolesRoute
  '/api/classes/create': typeof ApiClassesCreateRoute
  '/api/classes/finalize': typeof ApiClassesFinalizeRoute
  '/api/classes/section-asset': typeof ApiClassesSectionAssetRoute
  '/api/webhooks/ses': typeof ApiWebhooksSesRoute
  '/assessments/$assessmentId/preview': typeof AssessmentsAssessmentIdPreviewRoute
  '/api/internal/assets/delete': typeof ApiInternalAssetsDeleteRoute
  '/api/internal/assets/upload': typeof ApiInternalAssetsUploadRoute
  '/api/internal/cron/tick': typeof ApiInternalCronTickRoute
  '/api/internal/email/process': typeof ApiInternalEmailProcessRoute
  '/api/internal/email/send-result': typeof ApiInternalEmailSendResultRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/escalations': typeof ApiPublicHooksEscalationsRoute
  '/api/public/hooks/retry-failed': typeof ApiPublicHooksRetryFailedRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
  '/learn/courses/$courseId/study': typeof LearnCoursesCourseIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/email-testing': typeof EmailTestingRoute
  '/executive': typeof ExecutiveRoute
  '/invites': typeof InvitesRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/api/health': typeof ApiHealthRoute
  '/assessments/builder': typeof AssessmentsBuilderRoute
  '/assessments/templates': typeof AssessmentsTemplatesRoute
  '/attempt/$assignmentId': typeof AttemptAssignmentIdRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/classes/new': typeof ClassesNewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/hiring/reports': typeof HiringReportsRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/interviews/$sessionId': typeof InterviewsSessionIdRoute
  '/interviews/assessments': typeof InterviewsAssessmentsRoute
  '/learn/courses': typeof LearnCoursesRouteWithChildren
  '/notifications/schedules': typeof NotificationsSchedulesRoute
  '/notifications/templates': typeof NotificationsTemplatesRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/interviews': typeof InterviewsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/bootstrap': typeof ApiAuthBootstrapRoute
  '/api/auth/roles': typeof ApiAuthRolesRoute
  '/api/classes/create': typeof ApiClassesCreateRoute
  '/api/classes/finalize': typeof ApiClassesFinalizeRoute
  '/api/classes/section-asset': typeof ApiClassesSectionAssetRoute
  '/api/webhooks/ses': typeof ApiWebhooksSesRoute
  '/assessments/$assessmentId/preview': typeof AssessmentsAssessmentIdPreviewRoute
  '/api/internal/assets/delete': typeof ApiInternalAssetsDeleteRoute
  '/api/internal/assets/upload': typeof ApiInternalAssetsUploadRoute
  '/api/internal/cron/tick': typeof ApiInternalCronTickRoute
  '/api/internal/email/process': typeof ApiInternalEmailProcessRoute
  '/api/internal/email/send-result': typeof ApiInternalEmailSendResultRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/escalations': typeof ApiPublicHooksEscalationsRoute
  '/api/public/hooks/retry-failed': typeof ApiPublicHooksRetryFailedRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
  '/learn/courses/$courseId/study': typeof LearnCoursesCourseIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRouteWithChildren
  '/email-testing': typeof EmailTestingRoute
  '/executive': typeof ExecutiveRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/invites': typeof InvitesRoute
  '/learn': typeof LearnRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/api/health': typeof ApiHealthRoute
  '/assessments/builder': typeof AssessmentsBuilderRoute
  '/assessments/templates': typeof AssessmentsTemplatesRoute
  '/attempt/$assignmentId': typeof AttemptAssignmentIdRoute
  '/classes/$classId': typeof ClassesClassIdRoute
  '/classes/new': typeof ClassesNewRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/hiring/reports': typeof HiringReportsRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/interviews/$sessionId': typeof InterviewsSessionIdRoute
  '/interviews/assessments': typeof InterviewsAssessmentsRoute
  '/learn/courses': typeof LearnCoursesRouteWithChildren
  '/notifications/schedules': typeof NotificationsSchedulesRoute
  '/notifications/templates': typeof NotificationsTemplatesRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/bootstrap': typeof ApiAuthBootstrapRoute
  '/api/auth/roles': typeof ApiAuthRolesRoute
  '/api/classes/create': typeof ApiClassesCreateRoute
  '/api/classes/finalize': typeof ApiClassesFinalizeRoute
  '/api/classes/section-asset': typeof ApiClassesSectionAssetRoute
  '/api/webhooks/ses': typeof ApiWebhooksSesRoute
  '/assessments/$assessmentId/preview': typeof AssessmentsAssessmentIdPreviewRoute
  '/api/internal/assets/delete': typeof ApiInternalAssetsDeleteRoute
  '/api/internal/assets/upload': typeof ApiInternalAssetsUploadRoute
  '/api/internal/cron/tick': typeof ApiInternalCronTickRoute
  '/api/internal/email/process': typeof ApiInternalEmailProcessRoute
  '/api/internal/email/send-result': typeof ApiInternalEmailSendResultRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
  '/api/public/hooks/escalations': typeof ApiPublicHooksEscalationsRoute
  '/api/public/hooks/retry-failed': typeof ApiPublicHooksRetryFailedRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
  '/learn/courses/$courseId/study': typeof LearnCoursesCourseIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assessments'
    | '/assignments'
    | '/auth'
    | '/courses'
    | '/email-testing'
    | '/executive'
    | '/interviews'
    | '/invites'
    | '/learn'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/api/health'
    | '/assessments/builder'
    | '/assessments/templates'
    | '/attempt/$assignmentId'
    | '/classes/$classId'
    | '/classes/new'
    | '/courses/$courseId'
    | '/hiring/reports'
    | '/interview/$token'
    | '/interviews/$sessionId'
    | '/interviews/assessments'
    | '/learn/courses'
    | '/notifications/schedules'
    | '/notifications/templates'
    | '/assessments/'
    | '/courses/'
    | '/interviews/'
    | '/learn/'
    | '/api/assets/$'
    | '/api/auth/bootstrap'
    | '/api/auth/roles'
    | '/api/classes/create'
    | '/api/classes/finalize'
    | '/api/classes/section-asset'
    | '/api/webhooks/ses'
    | '/assessments/$assessmentId/preview'
    | '/api/internal/assets/delete'
    | '/api/internal/assets/upload'
    | '/api/internal/cron/tick'
    | '/api/internal/email/process'
    | '/api/internal/email/send-result'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/escalations'
    | '/api/public/hooks/retry-failed'
    | '/api/public/hooks/weekly-summary'
    | '/learn/courses/$courseId/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assignments'
    | '/auth'
    | '/email-testing'
    | '/executive'
    | '/invites'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/api/health'
    | '/assessments/builder'
    | '/assessments/templates'
    | '/attempt/$assignmentId'
    | '/classes/$classId'
    | '/classes/new'
    | '/courses/$courseId'
    | '/hiring/reports'
    | '/interview/$token'
    | '/interviews/$sessionId'
    | '/interviews/assessments'
    | '/learn/courses'
    | '/notifications/schedules'
    | '/notifications/templates'
    | '/assessments'
    | '/courses'
    | '/interviews'
    | '/learn'
    | '/api/assets/$'
    | '/api/auth/bootstrap'
    | '/api/auth/roles'
    | '/api/classes/create'
    | '/api/classes/finalize'
    | '/api/classes/section-asset'
    | '/api/webhooks/ses'
    | '/assessments/$assessmentId/preview'
    | '/api/internal/assets/delete'
    | '/api/internal/assets/upload'
    | '/api/internal/cron/tick'
    | '/api/internal/email/process'
    | '/api/internal/email/send-result'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/escalations'
    | '/api/public/hooks/retry-failed'
    | '/api/public/hooks/weekly-summary'
    | '/learn/courses/$courseId/study'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assessments'
    | '/assignments'
    | '/auth'
    | '/courses'
    | '/email-testing'
    | '/executive'
    | '/interviews'
    | '/invites'
    | '/learn'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/api/health'
    | '/assessments/builder'
    | '/assessments/templates'
    | '/attempt/$assignmentId'
    | '/classes/$classId'
    | '/classes/new'
    | '/courses/$courseId'
    | '/hiring/reports'
    | '/interview/$token'
    | '/interviews/$sessionId'
    | '/interviews/assessments'
    | '/learn/courses'
    | '/notifications/schedules'
    | '/notifications/templates'
    | '/assessments/'
    | '/courses/'
    | '/interviews/'
    | '/learn/'
    | '/api/assets/$'
    | '/api/auth/bootstrap'
    | '/api/auth/roles'
    | '/api/classes/create'
    | '/api/classes/finalize'
    | '/api/classes/section-asset'
    | '/api/webhooks/ses'
    | '/assessments/$assessmentId/preview'
    | '/api/internal/assets/delete'
    | '/api/internal/assets/upload'
    | '/api/internal/cron/tick'
    | '/api/internal/email/process'
    | '/api/internal/email/send-result'
    | '/api/public/hooks/daily-reminders'
    | '/api/public/hooks/escalations'
    | '/api/public/hooks/retry-failed'
    | '/api/public/hooks/weekly-summary'
    | '/learn/courses/$courseId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  AssignmentsRoute: typeof AssignmentsRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  EmailTestingRoute: typeof EmailTestingRoute
  ExecutiveRoute: typeof ExecutiveRoute
  InterviewsRoute: typeof InterviewsRouteWithChildren
  InvitesRoute: typeof InvitesRoute
  LearnRoute: typeof LearnRouteWithChildren
  NotificationsRoute: typeof NotificationsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AttemptAssignmentIdRoute: typeof AttemptAssignmentIdRoute
  ClassesClassIdRoute: typeof ClassesClassIdRoute
  ClassesNewRoute: typeof ClassesNewRoute
  HiringReportsRoute: typeof HiringReportsRoute
  InterviewTokenRoute: typeof InterviewTokenRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiAuthBootstrapRoute: typeof ApiAuthBootstrapRoute
  ApiAuthRolesRoute: typeof ApiAuthRolesRoute
  ApiClassesCreateRoute: typeof ApiClassesCreateRoute
  ApiClassesFinalizeRoute: typeof ApiClassesFinalizeRoute
  ApiClassesSectionAssetRoute: typeof ApiClassesSectionAssetRoute
  ApiWebhooksSesRoute: typeof ApiWebhooksSesRoute
  ApiInternalAssetsDeleteRoute: typeof ApiInternalAssetsDeleteRoute
  ApiInternalAssetsUploadRoute: typeof ApiInternalAssetsUploadRoute
  ApiInternalCronTickRoute: typeof ApiInternalCronTickRoute
  ApiInternalEmailProcessRoute: typeof ApiInternalEmailProcessRoute
  ApiInternalEmailSendResultRoute: typeof ApiInternalEmailSendResultRoute
  ApiPublicHooksDailyRemindersRoute: typeof ApiPublicHooksDailyRemindersRoute
  ApiPublicHooksEscalationsRoute: typeof ApiPublicHooksEscalationsRoute
  ApiPublicHooksRetryFailedRoute: typeof ApiPublicHooksRetryFailedRoute
  ApiPublicHooksWeeklySummaryRoute: typeof ApiPublicHooksWeeklySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-testing': {
      id: '/email-testing'
      path: '/email-testing'
      fullPath: '/email-testing'
      preLoaderRoute: typeof EmailTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/notifications/templates': {
      id: '/notifications/templates'
      path: '/templates'
      fullPath: '/notifications/templates'
      preLoaderRoute: typeof NotificationsTemplatesRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/notifications/schedules': {
      id: '/notifications/schedules'
      path: '/schedules'
      fullPath: '/notifications/schedules'
      preLoaderRoute: typeof NotificationsSchedulesRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/learn/courses': {
      id: '/learn/courses'
      path: '/courses'
      fullPath: '/learn/courses'
      preLoaderRoute: typeof LearnCoursesRouteImport
      parentRoute: typeof LearnRoute
    }
    '/interviews/assessments': {
      id: '/interviews/assessments'
      path: '/assessments'
      fullPath: '/interviews/assessments'
      preLoaderRoute: typeof InterviewsAssessmentsRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/interviews/$sessionId': {
      id: '/interviews/$sessionId'
      path: '/$sessionId'
      fullPath: '/interviews/$sessionId'
      preLoaderRoute: typeof InterviewsSessionIdRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/interview/$token': {
      id: '/interview/$token'
      path: '/interview/$token'
      fullPath: '/interview/$token'
      preLoaderRoute: typeof InterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/reports': {
      id: '/hiring/reports'
      path: '/hiring/reports'
      fullPath: '/hiring/reports'
      preLoaderRoute: typeof HiringReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/classes/new': {
      id: '/classes/new'
      path: '/classes/new'
      fullPath: '/classes/new'
      preLoaderRoute: typeof ClassesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classId': {
      id: '/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof ClassesClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt/$assignmentId': {
      id: '/attempt/$assignmentId'
      path: '/attempt/$assignmentId'
      fullPath: '/attempt/$assignmentId'
      preLoaderRoute: typeof AttemptAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/templates': {
      id: '/assessments/templates'
      path: '/templates'
      fullPath: '/assessments/templates'
      preLoaderRoute: typeof AssessmentsTemplatesRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/builder': {
      id: '/assessments/builder'
      path: '/builder'
      fullPath: '/assessments/builder'
      preLoaderRoute: typeof AssessmentsBuilderRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$assessmentId/preview': {
      id: '/assessments/$assessmentId/preview'
      path: '/$assessmentId/preview'
      fullPath: '/assessments/$assessmentId/preview'
      preLoaderRoute: typeof AssessmentsAssessmentIdPreviewRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/api/webhooks/ses': {
      id: '/api/webhooks/ses'
      path: '/api/webhooks/ses'
      fullPath: '/api/webhooks/ses'
      preLoaderRoute: typeof ApiWebhooksSesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/section-asset': {
      id: '/api/classes/section-asset'
      path: '/api/classes/section-asset'
      fullPath: '/api/classes/section-asset'
      preLoaderRoute: typeof ApiClassesSectionAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/finalize': {
      id: '/api/classes/finalize'
      path: '/api/classes/finalize'
      fullPath: '/api/classes/finalize'
      preLoaderRoute: typeof ApiClassesFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classes/create': {
      id: '/api/classes/create'
      path: '/api/classes/create'
      fullPath: '/api/classes/create'
      preLoaderRoute: typeof ApiClassesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/roles': {
      id: '/api/auth/roles'
      path: '/api/auth/roles'
      fullPath: '/api/auth/roles'
      preLoaderRoute: typeof ApiAuthRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/bootstrap': {
      id: '/api/auth/bootstrap'
      path: '/api/auth/bootstrap'
      fullPath: '/api/auth/bootstrap'
      preLoaderRoute: typeof ApiAuthBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/courses/$courseId/study': {
      id: '/learn/courses/$courseId/study'
      path: '/$courseId/study'
      fullPath: '/learn/courses/$courseId/study'
      preLoaderRoute: typeof LearnCoursesCourseIdStudyRouteImport
      parentRoute: typeof LearnCoursesRoute
    }
    '/api/public/hooks/weekly-summary': {
      id: '/api/public/hooks/weekly-summary'
      path: '/api/public/hooks/weekly-summary'
      fullPath: '/api/public/hooks/weekly-summary'
      preLoaderRoute: typeof ApiPublicHooksWeeklySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-failed': {
      id: '/api/public/hooks/retry-failed'
      path: '/api/public/hooks/retry-failed'
      fullPath: '/api/public/hooks/retry-failed'
      preLoaderRoute: typeof ApiPublicHooksRetryFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/escalations': {
      id: '/api/public/hooks/escalations'
      path: '/api/public/hooks/escalations'
      fullPath: '/api/public/hooks/escalations'
      preLoaderRoute: typeof ApiPublicHooksEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reminders': {
      id: '/api/public/hooks/daily-reminders'
      path: '/api/public/hooks/daily-reminders'
      fullPath: '/api/public/hooks/daily-reminders'
      preLoaderRoute: typeof ApiPublicHooksDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/email/send-result': {
      id: '/api/internal/email/send-result'
      path: '/api/internal/email/send-result'
      fullPath: '/api/internal/email/send-result'
      preLoaderRoute: typeof ApiInternalEmailSendResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/email/process': {
      id: '/api/internal/email/process'
      path: '/api/internal/email/process'
      fullPath: '/api/internal/email/process'
      preLoaderRoute: typeof ApiInternalEmailProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/cron/tick': {
      id: '/api/internal/cron/tick'
      path: '/api/internal/cron/tick'
      fullPath: '/api/internal/cron/tick'
      preLoaderRoute: typeof ApiInternalCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/assets/upload': {
      id: '/api/internal/assets/upload'
      path: '/api/internal/assets/upload'
      fullPath: '/api/internal/assets/upload'
      preLoaderRoute: typeof ApiInternalAssetsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/assets/delete': {
      id: '/api/internal/assets/delete'
      path: '/api/internal/assets/delete'
      fullPath: '/api/internal/assets/delete'
      preLoaderRoute: typeof ApiInternalAssetsDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsBuilderRoute: typeof AssessmentsBuilderRoute
  AssessmentsTemplatesRoute: typeof AssessmentsTemplatesRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  AssessmentsAssessmentIdPreviewRoute: typeof AssessmentsAssessmentIdPreviewRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsBuilderRoute: AssessmentsBuilderRoute,
  AssessmentsTemplatesRoute: AssessmentsTemplatesRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  AssessmentsAssessmentIdPreviewRoute: AssessmentsAssessmentIdPreviewRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface InterviewsRouteChildren {
  InterviewsSessionIdRoute: typeof InterviewsSessionIdRoute
  InterviewsAssessmentsRoute: typeof InterviewsAssessmentsRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
}

const InterviewsRouteChildren: InterviewsRouteChildren = {
  InterviewsSessionIdRoute: InterviewsSessionIdRoute,
  InterviewsAssessmentsRoute: InterviewsAssessmentsRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
}

const InterviewsRouteWithChildren = InterviewsRoute._addFileChildren(
  InterviewsRouteChildren,
)

interface LearnCoursesRouteChildren {
  LearnCoursesCourseIdStudyRoute: typeof LearnCoursesCourseIdStudyRoute
}

const LearnCoursesRouteChildren: LearnCoursesRouteChildren = {
  LearnCoursesCourseIdStudyRoute: LearnCoursesCourseIdStudyRoute,
}

const LearnCoursesRouteWithChildren = LearnCoursesRoute._addFileChildren(
  LearnCoursesRouteChildren,
)

interface LearnRouteChildren {
  LearnCoursesRoute: typeof LearnCoursesRouteWithChildren
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCoursesRoute: LearnCoursesRouteWithChildren,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface NotificationsRouteChildren {
  NotificationsSchedulesRoute: typeof NotificationsSchedulesRoute
  NotificationsTemplatesRoute: typeof NotificationsTemplatesRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsSchedulesRoute: NotificationsSchedulesRoute,
  NotificationsTemplatesRoute: NotificationsTemplatesRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  AssignmentsRoute: AssignmentsRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRouteWithChildren,
  EmailTestingRoute: EmailTestingRoute,
  ExecutiveRoute: ExecutiveRoute,
  InterviewsRoute: InterviewsRouteWithChildren,
  InvitesRoute: InvitesRoute,
  LearnRoute: LearnRouteWithChildren,
  NotificationsRoute: NotificationsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ApiHealthRoute: ApiHealthRoute,
  AttemptAssignmentIdRoute: AttemptAssignmentIdRoute,
  ClassesClassIdRoute: ClassesClassIdRoute,
  ClassesNewRoute: ClassesNewRoute,
  HiringReportsRoute: HiringReportsRoute,
  InterviewTokenRoute: InterviewTokenRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiAuthBootstrapRoute: ApiAuthBootstrapRoute,
  ApiAuthRolesRoute: ApiAuthRolesRoute,
  ApiClassesCreateRoute: ApiClassesCreateRoute,
  ApiClassesFinalizeRoute: ApiClassesFinalizeRoute,
  ApiClassesSectionAssetRoute: ApiClassesSectionAssetRoute,
  ApiWebhooksSesRoute: ApiWebhooksSesRoute,
  ApiInternalAssetsDeleteRoute: ApiInternalAssetsDeleteRoute,
  ApiInternalAssetsUploadRoute: ApiInternalAssetsUploadRoute,
  ApiInternalCronTickRoute: ApiInternalCronTickRoute,
  ApiInternalEmailProcessRoute: ApiInternalEmailProcessRoute,
  ApiInternalEmailSendResultRoute: ApiInternalEmailSendResultRoute,
  ApiPublicHooksDailyRemindersRoute: ApiPublicHooksDailyRemindersRoute,
  ApiPublicHooksEscalationsRoute: ApiPublicHooksEscalationsRoute,
  ApiPublicHooksRetryFailedRoute: ApiPublicHooksRetryFailedRoute,
  ApiPublicHooksWeeklySummaryRoute: ApiPublicHooksWeeklySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
